### ISSUE TITLE
http推送api接口与ws服务在一台机器上的疑问

### ISSUE THREAD

**Issue by lik0914** [noiron/socket-message-push#1]
如题，如果http 推送 api，与ws 在实际环境中，很有可能不在一太服务上吧， 或者说， ws 部署多台服务器了，这种情况，应该怎么处理呢？

**Comment by noiron** [comment]
这个项目里 websocket 服务器用的是4001端口，本地打开项目访问的是 localhost:4001。
在实际环境中把这个项目部署到服务器上会有一个对外的URL地址，假设你的服务器地址是 `www.example.com`，那就通过 `www.example.com:4001/api` 进行推送。不过正常情况下，不会直接用端口访问，服务器上需要用 Nginx 之类进行配置，将 4001 端口与某个 URL 对应起来，比如配置的是 `/websocket` 这个地址，那外界就可以用 `www.example.com/websocket/api` 来访问了。
